services:
  app:
    container_name: product_microservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
      - 5007:5007
    environment:
      - PORT=5555
    restart: always